version: '3.7'
services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: BookNetwork
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - book-network

  phpmyadmin8-container:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin8-container
    restart: always
    depends_on:
      - mysql8-container
    ports:
      - 8100:80
    environment:
      PMA_HOST: mysql8-container
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    networks:
      - book-network

networks:
  book-network:
    name: book-network
    driver: bridge